=== MozillaFoundation/foundation.mozilla.org/source/json/upcoming.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "photo": {
        "type": "string"
      },
      "startDate": {
        "type": ["string", "null"]
      },
      "endDate": {
        "type": ["string", "null"]
      },
      "headline": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "link": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "url",
          "description"
        ]
      }
    },
    "required": [
      "photo",
      "startDate",
      "endDate",
      "headline",
      "description",
      "link"
    ]
  }
}

=== MozillaFoundation/foundation.mozilla.org/source/json/upcoming.json
[{
  "photo": "/_images/dso.jpg",
  "startDate": "2017-03-01T08:00:00.000Z",
  "endDate": null,
  "headline": "Digital Skills Observatory (DSO) research published",
  "description": "DSO is a 12-month research project carried out by Mozilla and partners, and supported by the Bill & Melinda Gates Foundation. Research explores how low-income, first-time Internet users in Kenya experience online life.",
  "link": {
    "url": "#TODO",
    "description": "View the research"
  }
}]
